name: 🐛 Bug Report

body:
  - type: markdown
  attributes:
   value: Thanks for taking the time to file a bug report!
  - type: input
  attributes:
   label: Command?
   description: "What command did the bug happen in?"
  validations:
      required: true
