name: "Request a Feature"
description: "Suggest an idea for this bot"

body:
  - type: input
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: input
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: input
    attrbutes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: input
    attrbutes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
